[tool.poetry]
name = "projeto"
version = "0.1.0"
description = ""
authors = ["davidade300 <iaderinho@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
